name: Build Test and Deploy
on:
  push:
    branches:
      - deploy

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY_MAMA }}
      DEBUG: 'True'
      DATABASE_URL: 'sqlite:///db.sqlite3'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.3
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Tests
        run: |
          python manage.py migrate --noinput
          python manage.py test --parallel
          
  
  merge-to-master:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/deploy'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge deploy into main
        run: |
          git checkout master
          git merge origin/deploy --no-ff -m "Merge deploy into master [skip ci]"
          git push origin master
